apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-helmrelease
  namespace: cluster-config
spec:
  targetNamespace: kube-system
  releaseName: keda
  chart:
    spec:
      chart: keda
      version: '2.8.1'
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: cluster-config
      interval: 1m
  interval: 1m
  install:
    createNamespace: true  
  values:
    Image:
      keda:
        repository: acrpixelnetestest.azurecr.io/library/keda
      metricsApiServer:
        repository: acrpixelnetestest.azurecr.io/library/keda-metrics-apiserver
